### ISSUE TITLE
TeX Support

### ISSUE THREAD

**Issue by alsaibie** [ethan-ou/vscode-gift-preview#4]
Thank you for providing this valuable extension. It would make it much more useful if TeX math is supported as well, perhaps MathJax plugin? I'm not familiar with typescript much unfortunately.

**Comment by ethan-ou** [comment]
@alsaibie I'll need to test the support with Moodle but this would definitely be valuable. Do you have any examples of working TeX that have been successfully imported into Moodle?

**Comment by alsaibie** [comment]
Using the output from the examples [here](https://github.com/manuvazquez/py2gift/tree/master/examples), the tex output works fine as you can see in the following figure. Using Moodle 3.9 default settings, which uses a binary TeX filter on the server. It works well with MathJax as well.

![image](https://user-images.githubusercontent.com/4665132/89214746-0dd1f980-d5d0-11ea-8602-12367e0890c0.png)

And this is how a similar example currently looks like with the VSCode GIFT extension. 
![image](https://user-images.githubusercontent.com/4665132/89215188-d879db80-d5d0-11ea-9b92-94fe8fb05f67.png)

The gift file is attached:
[test.gift.txt](https://github.com/ethan-ou/vscode-gift-preview/files/5017697/test.gift.txt)

**Comment by ethan-ou** [comment]
Thanks for the examples. I just added a preliminary version of TeX support, so it should appear the next time you open VSCode. I tested the example you sent and it works perfectly. I'll keep this issue open until you've also tested the extension yourself.

**Comment by alsaibie** [comment]
Works great on my end. That's a time-saver, thanks.
